### ISSUE TITLE
doesn't handle multiple running players well

### ISSUE THREAD

**Issue by treeshateorcs** [InputUsername/rescrobbled#10]
I often have both cmus and ncspot running, but obviously only one is playing, and rescrobbled doesn't scrobble when one of the players is stopped

**Comment by InputUsername** [comment]
You're right. Currently the program retrieves the active player using [`PlayerFinder::find_active`](https://docs.rs/mpris/2.0.0-rc1/mpris/struct.PlayerFinder.html#method.find_active), but apparently this naively selects the first music player in the list of music players, even if another player is active.

Spotify only becomes inactive once the application is closed, what about cmus/ncspot?

**Comment by treeshateorcs** [comment]
I suggest using `PlayerFinder::find_all()`  and scrobble from the one that is currently playing

**Comment by InputUsername** [comment]
I've implemented simple handling for multiple players on the [`multiple-player-support`](https://github.com/InputUsername/rescrobbled/tree/multiple-player-support) branch. Could you check if this works for your use case?

**Comment by treeshateorcs** [comment]
seems to be working fine

**Comment by InputUsername** [comment]
Cool, thanks. Merged.
