### ISSUE TITLE
Cannot submit track without album to Last.fm

### ISSUE THREAD

**Issue by AzraAnimating** [InputUsername/rescrobbled#101]
I just installed and Configured rescrobbled from the newest provided release (0.7.0) and was trying to use it with Tidal-Hifi (https://github.com/Mastermindzh/tidal-hifi) on Ubuntu 22.10.

Sadly i keep getting this error: ``Cannot submit track without album to Last.fm``

**Comment by gbava** [comment]
I've solved it by installing the previous version (0.6.2)

**Comment by trivarialthea** [comment]
Any updates onto this issue? Will it be fixed? Also using tidal-hifi and have the same error.

**Comment by InputUsername** [comment]
@trivarialthea I haven't had time to work on rescrobbled for the past few months because of other commitments, but I do want to get back to work soon! (-ish, hopefully in the next few weeks)

>Also using tidal-hifi and have the same error.

Do you have any idea whether Tidal plays songs outside the context of an album?

In any case, the Last.fm API doesn't actually require the album to be scrobbledt, but the library rescrobbled uses does require it for some reason. I'll see if I can get a patch out soon.

**Comment by InputUsername** [comment]
@trivarialthea 

> I do not, but if there is some way i can verify it feel free to tell me the steps to do so and i can check!

If you could use [playerctl](https://github.com/altdesktop/playerctl), run `playerctl metadata` while playing a song that causes the error, and copy the result here, that would be very helpful!

**Comment by InputUsername** [comment]
@trivarialthea Thanks! Definitely looks like tidal-hifi is not reporting the album.

I found the following issue which seems related: https://github.com/Mastermindzh/tidal-hifi/issues/106 Apparently tidal-hifi can't detect the album a track is playing from, so it seems like a bug/limitation in tidal-hifi itself.

Obviously rescrobbled should still allow submitting songs without an album to Last.fm, I will try to address this.

**Comment by InputUsername** [comment]
@AzraAnimating @gbava @trivarialthea Sorry for the ping, but I have released [version 0.7.1](https://github.com/InputUsername/rescrobbled/releases/tag/v0.7.1) that (hopefully) fixes this and allows scrobbling tracks without an album. Please let me know if it works for you!

**Comment by AzraAnimating** [comment]
Thanks very much! I'll Check it later :)

**Comment by AzraAnimating** [comment]
I can confirm works flawlessly for me now! Thanks again! (Tested on Fedora 38 & Ubuntu 22.10)
