### ISSUE TITLE
Music submits twice

### ISSUE THREAD

**Issue by dibusure** [InputUsername/rescrobbled#103]
![image](https://user-images.githubusercontent.com/69085213/235649488-bf37e08c-0ab0-4911-a814-219892c9c8d1.png)
Track submits
![image](https://user-images.githubusercontent.com/69085213/235649549-9f280251-9133-4c62-911e-ed3be5f609c8.png)
And in last.fm its twice

**Comment by dibusure** [comment]
Filter:
```#!/usr/bin/env python3

import sys

# Filter scripts receive the track artist, title, album and comma-separated list of genre(s)
# on separate lines of their standard input...

artist, title, album, genres = (l.rstrip() for l in sys.stdin.readlines())
genres = genres.split(',')

# ...and should provide artist, title and album on the corresponding lines of the
# standard output

print(artist, title, album, sep='\n')```

**Comment by InputUsername** [comment]
@dibusure

> ...
> And in last.fm its twice

The top one is the currently playing song - it's not actually submitted :smile: Or are you saying all songs actually appear twice?

> Filter:
> ...

Btw, this looks like an example filter script, filter scripts are only useful if you want to change metadata or ignore certain songs.

**Comment by dibusure** [comment]
@InputUsername, oh i'm sorry 😅, thank you for explanation.
and how i disable the filter script? `filter-script=""`?
