### ISSUE TITLE
panic if network is down

### ISSUE THREAD

**Issue by treeshateorcs** [InputUsername/rescrobbled#12]
http://ix.io/1Um3

this should be easy to fix

**Comment by InputUsername** [comment]
Ah yes, that shouldn't happen, thanks for the report. I'll try to implement caching scrobbles, so they can be retried at a later moment when the network is working again.

**Comment by InputUsername** [comment]
It looks to be a problem in `listenbrainz-rust`. I've made an [issue](https://github.com/treeshateorcs/listenbrainz-rust/issues/1) for this.
