### ISSUE TITLE
Is it possible to install this for Windows using Musicbee?

### ISSUE THREAD

**Issue by Nowena** [InputUsername/rescrobbled#136]
I just want to scrobble songs under 30 seconds.

If this can be installed on windows, may you explain how? I tried with rust/cargo install, I got the pkgconfig thingy but now it is asking me for dbus-1 which seems to be linux stuff, then I am supposed to use gnome or MinGW or Chocolatey or whatever. I am way too tired for this.

I cannot find a simply Musicbee plugin or a simple windows .exe that does this. I just want my powerviolence/grindcore/emoviolence songs scrobbled.

**Comment by InputUsername** [comment]
I'm sorry, rescrobbled indeed uses D-Bus which is a Linux specific thing, so I don't think this will work on Windows. It looks like MusicBee has a bunch of plugins for scrobbling though, maybe you can try one of those? For example [ScrobbleItem](https://getmusicbee.com/addons/plugins/432/scrobbleitem/) looks promising.

**Comment by Nowena** [comment]
You have to manually scrobble with ScrobbleItem. It has a button. It is not automatic. I did ask the creator to make it automatic some months ago but there was never a response.

**Comment by InputUsername** [comment]
> You have to manually scrobble with ScrobbleItem. It has a button. It is not automatic. I did ask the creator to make it automatic some months ago but there was never a response.

That sucks :disappointed: I'm sorry I can't help here, I hope you manage to solve your problem!
