### ISSUE TITLE
No Installation instructions

### ISSUE THREAD

**Issue by aadilayub** [InputUsername/rescrobbled#15]

**Comment by InputUsername** [comment]
Hey, thanks for the report. I have improved the readme with installation and usage instructions, see #17. Could you have a look and check if you think this is sufficient? Cheers!

**Comment by aadilayub** [comment]
Sorry for responding to this late. I left some comments on the PR! Could you take a look at them?

**Comment by InputUsername** [comment]
No worries, I appreciate the help.
