### ISSUE TITLE
Add mechanism for launching rescrobbled in the background on startup

### ISSUE THREAD

**Issue by aadilayub** [InputUsername/rescrobbled#16]
It's a bit of a pain to manually run the executable each time I want my music to scrobble from cmus. Is there a way to launch rescrobbled in the background as soon my computer boots, so that everything I listened to gets scrobbled by default?

I tried creating and using the systemd unit file but it didn't seem to have any effect (i.e. my tracks were't scrobbling when I checked my last.fm page). They did start scrobbling as soon as I manually launched rescrobbled from cli though, even though I had already done `systemctl --user start rescrobbled.service`.

**Comment by InputUsername** [comment]
Hi, thanks for reporting this! Are you using the binary releases or are you installing using Cargo?

**Comment by aadilayub** [comment]
I'm using the binary release

**Comment by InputUsername** [comment]
Okay, could you try changing `ExecStart` in the systemd unit file to point to the binary? I will look into improving this/adding installation instructions.

**Comment by aadilayub** [comment]
@InputUsername changing ExecStart worked! thank you. 

Do I have to run `systemctl --user start rescrobbled.service` in every session now, or will it start running in the background on boot?

**Comment by InputUsername** [comment]
Awesome!

If I'm not mistaken, `systemctl --user enable rescrobbled.service` should make it run on boot. Then you can use `start` to start it in the current session. I'm not too experienced with systemd, but when I tried that it seemed to work for me. I will look into making this clearer in the readme!

**Comment by InputUsername** [comment]
@aadilayub I assume this fixes the issue for you?

**Comment by aadilayub** [comment]
It does! Sorry for not responding earlier. Everything works as expected. Tracks get scrobbled on cmus automatically.

**Comment by InputUsername** [comment]
Great, thank you!
