### ISSUE TITLE
ArchLinux AUR package

### ISSUE THREAD

**Issue by brycied00d** [InputUsername/rescrobbled#19]
Hi! I wanted to let you know that I put together an AUR package of rescrobbled for ArchLinux/AUR users. https://aur.archlinux.org/packages/rescrobbled-git/ Whether or not you choose to link to it is up to you of course, I just wanted to be sure you were aware of it.

**Comment by InputUsername** [comment]
Hi, thank you for doing this and letting me know! I'll add it to the Readme with a link to your profile (if that's okay with you?)

**Comment by brycied00d** [comment]
Sure thing, that'd be fine with me.

**Comment by InputUsername** [comment]
Done, thanks.
