### ISSUE TITLE
Allow ListenBrainz only

### ISSUE THREAD

**Issue by Forage** [InputUsername/rescrobbled#26]
Based on the documentation, and me waiting for the next release for the white-list feature before using rescrobbled, it appears it's mandatory to use Last.fm, even though people might only be interested in ListenBrainz submissions.

Would it be possible to remove this requirement and allow for only a ListenBrainz account?

**Comment by InputUsername** [comment]
That's correct, initially I only intended this as a small tool to scrobble directly to Last.fm, but it makes sense to make it optional!

Also I thought I had already released whitelist support but turns out I haven't, so I will do that ASAP as well.

Thanks for the suggestion!

**Comment by InputUsername** [comment]
I've just released [version 0.2.0](https://github.com/InputUsername/rescrobbled/releases/tag/v0.2.0) which includes this!

**Comment by Forage** [comment]
Great, much appreciated!
