### ISSUE TITLE
Error while loading config: No such file or directory (os error 2)

### ISSUE THREAD

**Issue by thornycrackers** [InputUsername/rescrobbled#33]
Hello! When I first run the rescrobbled executable I get this error. Should rescrobbled just create the config file if it doesn't exist yet?

**Comment by InputUsername** [comment]
Hi! By default rescrobbled expects the config to exist already, but it makes sense to create it if it doesn't exist. Thanks for the suggestion.

**Comment by InputUsername** [comment]
I've implemented this and it will be in the next release. Thanks again for the suggestion!
