### ISSUE TITLE
Example `config.toml` file has typos

### ISSUE THREAD

**Issue by isinyaaa** [InputUsername/rescrobbled#38]
`lastfm-token` should be `lastfm-key`. Took me a while to find out why it wasn't working.

**Comment by InputUsername** [comment]
Thanks for the report! I've released `v0.3.1` which fixes this.

**Comment by rdricco** [comment]
> `lastfm-token` should be `lastfm-key`. Took me a while to find out why it wasn't working.

Same here for `player-whitelist`.

**Comment by InputUsername** [comment]
Wow, you're right, the template is full of typos. That's honestly embarrassing 😅 Thanks for letting me know, I'll fix it ASAP.

**Comment by InputUsername** [comment]
Just published [`v0.3.2`](https://github.com/InputUsername/rescrobbled/releases/tag/v0.3.2) that fixes this.
