### ISSUE TITLE
Make API endpoints configurable

### ISSUE THREAD

**Issue by tdemin** [InputUsername/rescrobbled#43]
For now this project won't play well with custom scrobble servers, such as [Maloja](https://github.com/krateng/maloja), that support ListenBrainz API.

Unfortunately, `listenbrainz_rust` got the API URI hardcoded.

**Comment by InputUsername** [comment]
Thank you for this suggestion, I fully agree this would be a good feature to add.

I'm thinking of creating a ListenBrainz library (`listenbrainz_rust` is unmaintained and its repo is gone) with support for a configurable URL, and use that. Should hopefully not take too long.

**Comment by shymega** [comment]
@InputUsername Regards to Listenbrainz, I've been thinking of adding support for Listenbrainz to `rustfm-scrobble` -  https://github.com/InputUsername/rescrobbled/issues/41#issuecomment-885608079 - originally, I had planned to write a Listenbrainz library *specifically* for my scrobbler, but perhaps it *might* be a good idea to work together and add Listenbrainz support to `rustfm-scrobble`, as well as Libre.fm? I'm about to open an issue on that crate with the aforementioned proposal

**Comment by shymega** [comment]
See: https://github.com/dmfutcher/rustfm-scrobble/issues/24#issuecomment-885615632

**Comment by InputUsername** [comment]
This has been implemented in `v0.5.0`!

@tdemin I'm closing this issue for now, feel free to reopen if the current solution doesn't work for you.
