### ISSUE TITLE
Autogenerated config should have tighter permissions

### ISSUE THREAD

**Issue by gjabell** [InputUsername/rescrobbled#47]
Thanks for the project, just started using it and it's working great so far!

I noticed that when the configuration file is autogenerated it has default (in my case `644`) permissions, which are readable by everyone. Since this file will likely contain authentication secrets, it would be great if it were created with `600` permissions so it's only readable by the user that runs rescrobbled.

**Comment by InputUsername** [comment]
Great suggestion - shouldn't be too hard to implement, I will add this in the next release

Thanks!

**Comment by InputUsername** [comment]
I just realized this should also be the case for the session token, so I will fix the permissions for that as well.

**Comment by InputUsername** [comment]
This has been added on the development branch and will be released with `v0.5.0`!
