### ISSUE TITLE
Add option for apps that don't send track length

### ISSUE THREAD

**Issue by mwllgr** [InputUsername/rescrobbled#51]
I am using tidal-hifi as a Chromium/Electron app on Ubuntu 20.04 and only get the title/artist via MPRIS - nothing more, nothing less. To solve this, I currently only deleted the corresponding lines out of the source code and set the length to a constant of 30 seconds - which works in my case but I don't really like the solution.

I documented my changes here: https://github.com/Mastermindzh/tidal-hifi/pull/11#issuecomment-956143965  
There should be an option to ignore the missing track length.

**Comment by InputUsername** [comment]
Hmm, it definitely makes sense to add this. The difficult part is that rescrobbled will currently scrobble a song multiple times when the same song keeps playing, so a default playing time of 30 seconds would cause a 2 minute song to be scrobbled 4 times. Do you have any ideas to avoid that?

**Comment by mwllgr** [comment]
Thank you for the quick reply! I'm using rescrobbled with the changes as documented and it works fine - no songs scrobbled multiple times. Just one thing is a bit weird: While playing a song it's displayed twice on last.fm (one as "scrobbling right now" and one as "x seconds ago"), after the track is done the second one gets removed.

**Comment by InputUsername** [comment]
>I'm using rescrobbled with the changes as documented and it works fine - no songs scrobbled multiple times.

Interesting, I'll have to look into that then. Maybe the existing functionality is broken, haha.

>Just one thing is a bit weird: While playing a song it's displayed twice on last.fm (one as "scrobbling right now" and one as "x seconds ago"), after the track is done the second one gets removed.

I think this may be the "now playing" song? If you submit a "now playing" request to Last.fm it will typically disappear automatically after a while.

**Comment by InputUsername** [comment]
>Also, just to keep you updated: Someone added code to include the song duration and artist via MPRIS so if I'm lucky I might not even need this patch in the future anymore :)

Thanks for the update! I unfortunately haven't had any time to look into this yet, so I would love to hear if the patch ends up not being needed. :)

**Comment by mwllgr** [comment]
Pull request merged. From my side: I do not need the implementation of this feature in rescrobbled anymore. Feel free to close the issue - thanks again for your quick replies!

**Comment by InputUsername** [comment]
Awesome, thanks for keeping me in the loop! I'll close this issue now.
