### ISSUE TITLE
listenbrainz authentication failure

### ISSUE THREAD

**Issue by bayang** [InputUsername/rescrobbled#57]
Hi, thanks for your project !

I was impatient to get support for custom listenbrainz servers since I'm a maloja user, unfortunately I couldn't manage to authenticate

Rescrobbled version is latest, built locally from source

Config (cleaned) looks like that : 

```
[[listenbrainz]]
url = "https://my_maloja_host/apis/listenbrainz"
token = "my_token"
```

Url and token work in other apps.

Error is : 
```
Authenticated with Last.fm successfully!
Failed to authenticate with ListenBrainz (https://my_maloja_host/apis/listenbrainz)
Looking for an active MPRIS player...
```

I can provide url and token in private if you want.

**Comment by InputUsername** [comment]
Thanks for the report! That's very strange, and I also don't understand why the error isn't giving more details... it should.

>I can provide url and token in private if you want.

That would be very helpful! You can find my email on my profile.

**Comment by InputUsername** [comment]
It turns out this was caused by a wrong URL: Maloja's ListenBrainz endpoint is `/apis/listenbrainz/1/`, not `/apis/listenbrainz`. Still, the lack of a descriptive error message is a bug that I will look into.

**Comment by InputUsername** [comment]
Error handling has been improved in `v0.5.2` so in the future it should be easier to determine why authentication went wrong!
