### ISSUE TITLE
add binaries

### ISSUE THREAD

**Issue by treeshateorcs** [InputUsername/rescrobbled#6]

**Comment by treeshateorcs** [comment]
don't forget to strip the binaries, if you are going to upload them

**Comment by InputUsername** [comment]
Good idea, I will do this when your other issues/PRs are resolved for a proper release.

**Comment by InputUsername** [comment]
Do you know what the recommended way of stripping binaries is for Rust?

**Comment by treeshateorcs** [comment]
`strip ./rescrobbled`

:^)

**Comment by treeshateorcs** [comment]
the stripped binary is 3 megabytes smaller

**Comment by InputUsername** [comment]
Looks like `cargo build --release` already strips the binary. Anyway, I've released the current version as `v0.1.0`!
