### ISSUE TITLE
Failed to update status on Last.fm

### ISSUE THREAD

**Issue by imNel** [InputUsername/rescrobbled#62]
Hi, I'm having trouble scrobbling.

I logged in with username and password as well as put my key and secret into the config file.
Anything obvious I'm doing wrong? Seems like I'm connecting to last.fm fine but just can't scrobble.

Application output:
```
Authenticated with Last.fm successfully!
Looking for an active MPRIS player...
Found active player Spot
----
Now playing: Porter Robinson - Divinity (Worlds)
Failed to update status on Last.fm
```

Any help would be greatly appreciated :)

Edit (Adding OS Details):
Fedora 35 x86_64
Installed via crates.io

**Comment by imNel** [comment]
Deleted `~/.config/rescrobbled/session` and re-logged in and my problem is solved!
Maybe my password was entered incorrectly? Not sure since I was able to authenticate successfully apparently :/

**Comment by InputUsername** [comment]
I've had this happen before too, not sure what caused it (could be a bug in Last.fm or the library I'm using) Glad it fixed itself!
