### ISSUE TITLE
Dependency on notify-rust 4.5.6... are previous versions compatible

### ISSUE THREAD

**Issue by gbcox** [InputUsername/rescrobbled#66]
I'm looking at packaging rescrobbled for fedora and ran into an issue with notify-rust.  Apparently there are some packages in Fedora that aren't compatible with 4.5.6 due to the changes to zbus/zvariant so that is holding up the ability to upgrade to 4.5.6 or greater.  

My question is will 4.5.3 for example work fine?  Thanks!

**Comment by InputUsername** [comment]
Hi, I just built with notify-rust 4.5.3 and it compiles and works perfectly fine. In fact before rescrobbled v0.5.2 the version of notify-rust was only pinned at major version 4, so *in theory* any 4.x.y release should work.

Is there anything else I need to do? (eg. downgrade notify-rust from 4.5.6 to 4.5.3)

Thanks!

**Comment by InputUsername** [comment]
@gbcox Not sure if it helps in any way, but I just released 0.7.0 which removes the dependency on notify-rust altogether.

**Comment by InputUsername** [comment]
Closing this for now, feel free to reopen or make another issue if there's anything I can help with to get a Fedora package working.
