### ISSUE TITLE
Do you know...

### ISSUE THREAD

**Issue by bonelifer** [InputUsername/rescrobbled#73]
Do you know of a script that allows you to feed in ARTIST and SongInfo and have it love that track on lastfm?  Everyone I've tried either didn't compile, needed libraries no longer work, or the closest I got was a perl script but it uses the old auth format that lastfm doesn't support anymore. I just need something I can run via keyboard shortcuts.

**Comment by InputUsername** [comment]
I don't think there are any ready-made scripts, but have you looked into [pylast](https://github.com/pylast/pylast)? From what I've seen it looks like a pretty comprehensive and easy-to-use Last.fm library.

Apologies for the late reply!

**Comment by bonelifer** [comment]
That's alright, I had forgotten I asked this here. Else I would of updated the issue. Yes, the Pylast author helped me make their readme.md example work. Apparently LastFM has been at it again changing stuff and the auth stuff didn't work.  I have the resulting code here in case someone else finds it useful.  https://github.com/bonelifer/mpd-scripts

**Comment by InputUsername** [comment]
Thanks for the update! Does this mean this issue can be closed?

>It'd probably be a good idea to enable discussion and convert this issue to a discussion so more people see it.

Do you mean on this repo?

**Comment by bonelifer** [comment]
Yes to both.
