### ISSUE TITLE
Duplicate scrobbles being submitted

### ISSUE THREAD

**Issue by arusahni** [InputUsername/rescrobbled#78]
Thanks for this - it's a lifesaver. However, I'm encountering a strange and intermittent issue: occasionally, rescrobbled will scrobble the same song multiple times. An example from the logs:

```
Jul 22 09:30:37 rescrobbled[871790]: Now playing: Ty Segall - Hello, Hi ("Hello, Hi")
Jul 22 09:30:37 rescrobbled[871790]: Status updated on Last.fm successfully
Jul 22 09:30:38 rescrobbled[871790]: Track submitted to Last.fm successfully
Jul 22 09:32:34 rescrobbled[871790]: Track submitted to Last.fm successfully
Jul 22 09:34:30 rescrobbled[871790]: Track submitted to Last.fm successfully
Jul 22 09:36:27 rescrobbled[871790]: Track submitted to Last.fm successfully
```

Any advice on how to best troubleshoot or debug this?

**Comment by InputUsername** [comment]
Thanks for the report!

Are you listening to this song on repeat? Looking at the timestamps, it looks like the song is being submitted at an interval that matches the song duration.

**Comment by InputUsername** [comment]
Ignore my previous comment if you saw it - my math was off.

The question stands though, are you listening to this song on repeat?

**Comment by arusahni** [comment]
I am not.

**Comment by InputUsername** [comment]
Very strange. How often does this happen? Is it completely at random?

**Comment by arusahni** [comment]
It's been happening fairly often. Right now, despite restarting the service and my music player ([tidal-hifi](https://github.com/Mastermindzh/tidal-hifi)), it's regularly submitting multiple scrobbles.

**Comment by arusahni** [comment]
I think this may be a bug with tidal-hifi (tracking [here](https://github.com/Mastermindzh/tidal-hifi/issues/154)). I'm going to close this until that gets shaken out.

**Comment by InputUsername** [comment]
Thank you for the update!
