### ISSUE TITLE
No scrobbling services defined

### ISSUE THREAD

**Issue by elecu** [InputUsername/rescrobbled#84]
Hi! I added my API key and shared secret to ~/.config/rescrobbled/config.toml, but the terminal shows the message "Warning: no scrobbling services defined".

I tried creating a new API, but the same issue. Should I add an URL to the API request from last.fm before making it?

**Comment by elecu** [comment]
Sorry, it was a very dumb question. I just noticed that I need to uncomment the lines in config.toml.

**Comment by InputUsername** [comment]
No worries! Glad you've managed to solve it 😄
