### ISSUE TITLE
Error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by Forage** [InputUsername/rescrobbled#87]
Hi,

rescrobbled unfortunately stopped working because Ubuntu moved from libssl1 to libssl3.
I'm now getting the following error:

`./rescrobbled: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

Should rescrobbled not switch as well?

Version: 0.6.1
OS: Ubuntu 22.10

**Comment by InputUsername** [comment]
Thanks for reporting, I'll get on this ASAP.

**Comment by InputUsername** [comment]
Ok, I've finally had time to dig into this, sorry for the massive delay :disappointed: 

Rescrobbled just links to whatever OpenSSL is installed at build time, so building from source as a temporary workaround should fix the issue. Starting from the next release, binaries on GitHub will link to libssl3.

Does this answer your issue?

**Comment by InputUsername** [comment]
In any case, I've just released 0.7.0. The GitHub binary now uses libssl3.

**Comment by Forage** [comment]
Works like a charm, many thanks!
